@startuml
'https://plantuml.com/class-diagram

interface Resource {
    InputStream getInputStream() throws IOException;
}

class ClassPathResource {
    private final String path;
    private ClassLoader classLoader;
}

class FileSystemResource {
    private final File file;
    private final String path;
}

class UrlResource {
    private final URL url;
}

interface ResourceLoader {
    String CLASSPATH_URL_PREFIX;
    Resource getResource(String location);
}

class DefaultResourceLoader implements ResourceLoader {
}

interface BeanDefinitionReader {
    BeanDefinitionRegistry getRegistry();
    ResourceLoader getResourceLoader();
    void loadBeanDefinitions(Resource resource) throws BeansException;
    void loadBeanDefinitions(Resource... resources) throws BeansException;
    void loadBeanDefinitions(String location) throws BeansException;
}

abstract class AbstractBeamDefinitionReader implements BeanDefinitionReader {
    private final BeanDefinitionRegistry registry;
    private final ResourceLoader resourceLoader;
    BeanDefinitionRegistry getRegistry();
    ResourceLoader getResourceLoader();
}

class XmlBeanDefinitionReader extends AbstractBeamDefinitionReader {
    void loadBeanDefinitions(Resource resource) throws BeansException;
    void loadBeanDefinitions(Resource... resources) throws BeansException;
    void loadBeanDefinitions(String location) throws BeansException;
}

interface BeanDefinitionRegistry {
    void registerBeanDefinition(String name, BeanDefinition beanDefinition);
    boolean containsBeanDefinition(String beanName);
}

'依赖
Resource <.. ResourceLoader

Resource <|.up. ClassPathResource
Resource <|.up. FileSystemResource
Resource <|.up. UrlResource

ResourceLoader <.right.. AbstractBeamDefinitionReader

BeanDefinitionRegistry <.left.. XmlBeanDefinitionReader
@enduml